### PR TITLE
Sign in flow

### LINKED ISSUE #158: Firebase auth errors in UI
When a user performs an erroneous action such as signing up with an email that already exists, display feedback to inform them. 

- [x] sign in with wrong password
- [x] sign in with invalid email or user not found
- [x] create account with an email that already exists

### PR DESCRIPTION
**Pull request by Carla-Moz**
This PR includes three changes: 

1. It updates the sign-in page with the new sign-in, create-acct flow
2. Adds firebase errors to the UI: 
      -  sign-in with wrong pw
      -  signin with invalid email or user not found
      -  create account with an email that already exists
3. Updates the ux tests to according the new flow

closes #158

### CODE REVIEW

File: src/lib/components/auth-cards/CheckEmailCard.svelte [hunk 1]
```diff
@@ -4,20 +4,20 @@
...
-  import "../../components/RallyDialog.css";
+  import "./Auth.css";
 
   const dispatch = createEventDispatcher();
 
   export let title;
   export let body;
-  export let bodyText;
-  export let linkText;
+  // export let bodyText;
```
Comment (rhelmer) [inline src/lib/components/auth-cards/CheckEmailCard.svelte:13]: Is there any benefit to leaving these in but commented-out?

File: src/lib/components/auth-cards/CheckEmailCard.svelte [hunk 2]
```diff
@@ -45,10 +45,20 @@
...
+    {#if !checkPW}
+      <p class="body-text-action">
+        Ready to sign in?<button
+          on:click={() => {
+            handleTrigger("welcome");
+          }}>Sign in</button
+        >
+      </p>
+    {/if}
+    <!-- <p class="body-text-action">
```
Comment (rhelmer) [inline src/lib/components/auth-cards/CheckEmailCard.svelte:57]: Same question wrt commented-out code, if we're going to use it in the near future it's fine, but otherwise I'd just delete it.

File: src/lib/components/auth-cards/LaunchCard.svelte [hunk 3]
```diff
@@ -89,15 +95,15 @@
         textColor="#000000"
         background="transparent"
         borderColor="#000000"
-        custom="card-button"
+        custom = "card-button"
+        btnID = {welcomeCard ? "signin" : "create"}
+        on:click={() => {
+          welcomeCard ? handleTrigger("signin") : handleTrigger("create");
+          console.log("THIS IS A HIT ON LAUNCH CARD")
```
Comment (rhelmer) [inline src/lib/components/auth-cards/LaunchCard.svelte:102]: Is this just for debugging?

**Review by rhelmer — CHANGES_REQUESTED** [review]
The code lgtm, I left a few comments wondering if we can remove commented-out code vs. leaving it, but if you have plans for it it's fine.

Two things I noticed while testing:

1. the font on the sidebar looks different, is this intentional?
Screen Shot 2021-11-17 at 8 25 25 AM
2. I'm seeing different variations of this stack trace on startup:

```
8:24:03 AM [vite] Error when evaluating SSR module /Users/mozilla/src/rally-web-platform/src/routes/__layout.svelte:
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65402:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65471:22)
    at /Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66410:34
    at String.replace (<anonymous>)
    at /Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66400:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66399:10)
    at instantiateModule (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66544:28)
```

From a quick search it looks like it's something specific to vite's SSR in dev mode, maybe introduced in a recent update? It doesn't seem to be causing test failures and nothing I can find wrong while testing, but it'd be good to understand why it's happening.

**Comment by rhelmer** [comment]
> The code lgtm, I left a few comments wondering if we can remove commented-out code vs. leaving it, but if you have plans for it it's fine.
> 
> Two things I noticed while testing:
> 
>     1. the font on the sidebar looks different, is this intentional?


For reference, on staging it looks like:

image

File: src/lib/components/auth-cards/LaunchCard.svelte (hunk 3 above)
Comment (Carla-Moz) [reply src/lib/components/auth-cards/LaunchCard.svelte:102]: Yes! I realized after that I forgot to delete it.

**Comment by Carla-Moz** [comment]
> The code lgtm, I left a few comments wondering if we can remove commented-out code vs. leaving it, but if you have plans for it it's fine.
> 
> Two things I noticed while testing:
> 
>     1. the font on the sidebar looks different, is this intentional?
> 
> 
> Screen Shot 2021-11-17 at 8 25 25 AM
> 2. I'm seeing different variations of this stack trace on startup:
> 
> ```
> 8:24:03 AM [vite] Error when evaluating SSR module /Users/mozilla/src/rally-web-platform/src/routes/__layout.svelte:
> TypeError: Line must be greater than or equal to 1, got -1
>     at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65402:13)
>     at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65471:22)
>     at /Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66410:34
>     at String.replace (<anonymous>)
>     at /Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66400:21
>     at Array.map (<anonymous>)
>     at ssrRewriteStacktrace (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66399:10)
>     at instantiateModule (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66544:28)
> ```
> 
> From a quick search it looks like it's something specific to vite's SSR in dev mode, maybe introduced in a recent update? It doesn't seem to be causing test failures and nothing I can find wrong while testing, but it'd be good to understand why it's happening.



> The code lgtm, I left a few comments wondering if we can remove commented-out code vs. leaving it, but if you have plans for it it's fine.
> 
> Two things I noticed while testing:
> 
>     1. the font on the sidebar looks different, is this intentional?
> 
> 
> Screen Shot 2021-11-17 at 8 25 25 AM
> 2. I'm seeing different variations of this stack trace on startup:
> 
> ```
> 8:24:03 AM [vite] Error when evaluating SSR module /Users/mozilla/src/rally-web-platform/src/routes/__layout.svelte:
> TypeError: Line must be greater than or equal to 1, got -1
>     at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65402:13)
>     at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:65471:22)
>     at /Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66410:34
>     at String.replace (<anonymous>)
>     at /Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66400:21
>     at Array.map (<anonymous>)
>     at ssrRewriteStacktrace (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66399:10)
>     at instantiateModule (/Users/mozilla/src/rally-web-platform/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66544:28)
> ```
> 
> From a quick search it looks like it's something specific to vite's SSR in dev mode, maybe introduced in a recent update? It doesn't seem to be causing test failures and nothing I can find wrong while testing, but it'd be good to understand why it's happening.

This is weird re the sidebar styles cause I don't see it on my local. I'll do another review of the CSS again. Most likely forgot to update some styles or something. As for the vite error, I'll investigate as well. Don't want it to potentially break something down the line.

**Review by rhelmer — APPROVED** [review]

**Review by stansky — APPROVED** [review]
