### PR TITLE
Fix footer

### LINKED ISSUE #261: Navigation: Top header, sidebar for account settings, account dropdown
### Account Dropdown
 - What is in it?
 - What is the design (dropdown, links, etc)?
 - Does it really need a photo (where will it bring in a photo)? Can it be an icon? (very low priority)

### Sidebar 
- What is it in?
- What is the design (spacing)?
- Behavior
- - Default open
- - Collapsable 
- Icons

### Navigation
- [x] Top nav
- [x] Account Dropdown
- [x] Sidebar
- [x] footer

## Sidebar nav

[link to Figma component](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=1923%3A22118)
Screen Shot 2022-05-12 at 12 00 48 PM

Screen Shot 2022-05-12 at 12 04 45 PM

## Top Nav

[Link to external link icon asset](https://drive.google.com/file/d/19e3GH8U1cn6KKfXq2u0xFVOJZ12JsJay/view?usp=sharing)

[Link to Figma component](https://www.figma.com/file/pw2RT5720W29pQEWSUTpy7/Mozilla-Rally-%E2%80%93%C2%A0Library?node-id=1827%3A943)
Screen Shot 2022-05-12 at 12 13 33 PM

### States: 

Default, Hover, On-state

Screen Shot 2022-05-12 at 12 43 20 PM

## Account Dropdown

[link to Figma](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=2967%3A61598)

### States:

**Default**

Screen Shot 2022-05-12 at 12 22 53 PM

**Hover/ Press/ On-state** 

Screen Shot 2022-05-12 at 12 29 44 PM

Screen Shot 2022-05-12 at 12 22 10 PM

Update: This is what I currently have for the footer, @tangcasey, could you please tell me what needs to be included or removed. Thanks.
 Footer:
Screen Shot 2022-05-20 at 9 28 41 AM

### LINKED ISSUE #428: [Bug] Clicking away from account dropdown doesn't close it
**Describe the bug**

**To Reproduce**
1. Go to /studies
2. Click the user icon to expand the dropdown menu
3. click anywhere on the screen away from the menu

Menu stays open

**Expected behavior**
Expect menu to close

**Screenshots**
image

### LINKED ISSUE #459: [Bug] small-width version of menu is empty on first load
**Describe the bug**

If the screen width is under the 960px breakpoint, then it is empty on first load

**To Reproduce**
1. Go to https://members.rally.mozilla.org
2. create account and sign in
3. reduce width of browser window below 1000px

**Expected behavior**

The menu is populated on first interaction

**Screenshots**
image

If I expand the width, interact with the menu, and then reduce it again, then it works:

image

**Browser / OS:**
 
**Additional context**

### PR DESCRIPTION
**Pull request by Carla-Moz**
This PR adds the responsive footer back to the platform and fixes two bugs: fading header dropdown when click outside the dropdown and showing the mobile menu. 

closes #428 
closes #459 
closes #261 

Added responsive footer to the RWP:
Screen Shot 2022-05-24 at 1 21 18 AM

### CODE REVIEW

**Comment by jepstein** [comment]
while this does mostly fix https://github.com/mozilla-rally/rally-web-platform/issues/428, I am still seeing some irregularity with the menu opening and closing that I will try to reproduce consistently and file a new issue.

**Review by jepstein — APPROVED** [review]

File: src/lib/views/account-settings/SigninSettings.svelte [hunk 1]
```diff
@@ -42,12 +42,11 @@
   });
 
   const getLatestVerified = async () => {
-   return isUserVerified = await store.isUserVerified();
-   
+    return (isUserVerified = await store.isUserVerified());
```
Comment (thomik-corp) [inline src/lib/views/account-settings/SigninSettings.svelte:45]: I don't see isUserVerified defined anywhere. In general we should not do assignments and returns on a single statement or in the same function. We can either do refreshLatestVerfied and refresh the state or we should just return the store value and use caller site to update the variable.

Comment (thomik-corp) [reply src/lib/views/account-settings/SigninSettings.svelte:45]: This is owing to reactive syntax of Svelte. I just learnt this.
